[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=4CD361DB4259A991CF0A2087FF5B6FAF
ProjectName=Project_2024
ProjectVersion=0.0.0.0
Description=Prototype

[StartupActions]
#bAddPacks=True
#InsertPack=(PackSource="StarterContent.upack",PackName="StarterContent")

